#' @title Fit ssanova with sampling model.
#'
#' @description  Do adaptive sampling and then fit ssanova model with Gusssian noise.
#' Return the fitmodel of function \code{gss::ssanova}
#'
#' @details  If x is a matrix, generate a data.frame of x & y;
#'   generate string of formular for high demesion like: \code{"y ~ x1 * x2 * ... * xn"}.
#'   Do not plot if x is a matrix.
#'
#'   When use function: \code{predict()}, follow the naming scheme as "x1, x2, ... xn"
#'   in new data.frame
#'
#' @param x         A vector (or a matrix or data.frame) of independent varibles.
#' (But now, we just realize vector part)
#' @param y         A vector of response varibles with noise
#'
#' @param alpha     A number of modifying minimizing GCV in \code{gss::ssanova}. Default = NULL (1.4).
#' @param nbasis    A number of approximate sample size in adaptive sample.
#'                  If it is \code{NULL}, the default number is \code{max(30, 10*n^(2/9))}.
#' @param nslice    A number of slices numbers. If \code{sliceMethod} is not \code{NULL}, it will be invaid.
#' @param sliceMethod A string of slice method among "Scott","Sturges", "FD"(Freddman and Diaconis).
#'                    The default is \code{NULL} (NULL is not a string).
#'                    The number of slices depends on the method.
#' @param returnIndex A boolean whether return index of samples.
#' @param plotFit   A boolean to plot saccter of (x,y), the samples and the smoothing curve.
#'
#' @return A list of fitted model generated by \code{gss::ssanova}.
#'
#'         If required return index of samples, return a list named \code{fitModel}(list)
#'         and \code{sample.index}(vector).
#'
#' @import stats
#' @export
#'
adap.ssanova <- function(x, y, alpha=NULL, nbasis=NULL, nslice=10, sliceMethod=NULL,
                         returnIndex = FALSE, plotFit = FALSE){

  # do adaptive sampling
  samples.index <- adap.sample(y, nbasis=nbasis, nslice=nslice, sliceMethod=sliceMethod)

  # In case the x is a matirx or data.frame(>=2D) instead of a vector(1D)
  # generate a string of spline formula and a data.frame containing x and y
  #
  ## x.dim is the number of columns of matrix x
  ## xy.df is a data.frame combined x and y, renamed cols as x1, x2, ..., y
  ## spline.formula is like "y ~ x1 * x2 * ... * xn"
  formula.and.df <- gen.formula.and.df(x, y)
  x.dim <- formula.and.df$x.dim
  xy.df <- formula.and.df$xy.df
  spline.formula <- formula.and.df$spline.formula
  rm(formula.and.df)

  # do fit model by ssanova in package: "gss"
  if(is.null(alpha)){
    fitModel <- gss::ssanova(spline.formula, data = xy.df, id.basis=samples.index)
  }else{
    fitModel <- gss::ssanova(spline.formula, data = xy.df, id.basis=samples.index, alpha=alpha)
  }


  # plot if required
  if((plotFit == TRUE) &(x.dim == 1)){
    fit.plot(x = x, y = y, sampleIndex=samples.index, fitModel=fitModel,
             figTitle="scatter and smoothing spline")
  }

  # return model or model and index of samples
  if(returnIndex == TRUE){
    return(list(fitModel = fitModel, sampleIndex = samples.index))
  }else{
    return(fitModel)
  }

}
